### ISSUE TITLE
Show command

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/cyberark-conjur-cli#218]
## **Feature Overview & Customer Need**

**As a**  Conjur user 
**I would like to** use the Conjur CLI 
**In order to** understand the status of Conjur object

*
A new command will be called **show** that will show the status of an object.
The commands will be used as follow:

`Conjur show -k layer -i app-layer
`
Args description:

-k  --kind <object kind value > - **Optional** provide the object kind  only the following items are supported: user|host|layer|group|policy|variable|webservice
^As a user can configure the same ID for different objects with two different types, we need to enable the user to filter it according to the object ID as well.
!!! NOTE -  If the kind always appear in the id of user|host|layer|group|policy|variable|webservice then this flag can be removed !!!

-i  --id < object identifier value > - provide the object identifier

Expected behavior should not change from the corresponding command in Ruby CLI 
@sharonr78 should provide the right help screen
Help is according to https://ljfz3b.axshare.com/#id=s9nycf&p=conjur_help__policy&g=1

## Process logic and Demo

Conjur user with a machine that the Python CLI already been installed and conjur init & login run against a Conjur/ Conjur Enterprise machine with the following resources & roles

Given the following resources & roles:
```
conjur list
[
  "demo:policy:root",
  "demo:policy:server",
  "demo:policy:ansible",
  "demo:layer:ansible",
  "demo:host:ansible/ansible-01",
  "demo:host_factory:ansible",
  "demo:variable:server/host1/host",
  "demo:variable:server/host1/user",
  "demo:variable:server/host1/pass",
  "demo:variable:server/host2/host",
  "demo:variable:server/host2/user",
  "demo:variable:server/host2/pass",
  "demo:group:server/secrets-users"
]
```

```
conjur show -i "demo:policy:root
{
  "created_at": "2021-03-07T14:49:38.524+00:00",
  "id": "demo:policy:root",
  "owner": "demo:user:admin",
  "permissions": [

  ],
  "annotations": [
  ],
  "policy_versions": [
    {
      "version": 1,
      "created_at": "2021-03-07T14:49:38.524+00:00",
      "policy_text": "- !policy\n  id: server\n\n- !policy\n  id: ansible\n",
      "policy_sha256": "c510db048dc18f33bb4aec00bd1e27cb4687e185d06836e0008ae539f9811f1f",
      "finished_at": "2021-03-07T14:49:38.638+00:00",
      "client_ip": "172.19.0.4",
      "id": "demo:policy:root",
      "role": "demo:user:admin"
    }
  ]
}

```
```
conjur show -i "ansible" 
Error stating that there are 2 options

conjur show -i "ansible" -k layer
{
  "created_at": "2021-03-07T14:49:41.995+00:00",
  "id": "demo:layer:ansible",
  "owner": "demo:policy:ansible",
  "policy": "demo:policy:ansible",
  "permissions": [

  ],
  "annotations": [

  ]
}
```
`conjur show -i "host/ansible/ansible01" -k host
`
Demo each option that was implemented
Show an existing object from all types possibles

Update an object and show it after change.

Delete objects from each type by using !delete in a policy
Show that the deleted object does not exists yet others are found

## Quality

Make sure we have test coverage of the show command.  Create test plan and execute accordingly.

## User messages

All user messages regarding object show should be reviewed

Especially error messages 

if an argument is missing we need to return the help of the command 

## **Documentation**

Please provide enhance documentation in online help and readme

## DOD

- [ ] Implement the show command Conjur Python CLI in all 3 platforms
- [ ] Demo the flow described above
- [ ] Automatic integration tests written according to a test plan and passed successfully
- [ ] Fill in the user messages - link to a page with all user messages for CLI saved and reviewed. 
- [ ] Fill in the logs and place here a link to the logs files - link to a page with all logs for CLI saved and reviewed. 
- [ ] Logs were reviewed by TW and PO
- [ ] Are there new Audits to this feature? If so please document them and provide here a link (N/A)

**Comment by szamir1** [comment]
@InbalZilberman 
added the following under the logic section

The commands will be used as follow:
Conjur show -o OBJECT_TYPE -i OBJECT_ID

-o --object - provide the object identifier
-I –object-id provide the object’s ID


Given the following resources & roles:
[
  "MyAccount:policy:root",
  "MyAccount:user:alice",
  "MyAccount:user:bob",
  "MyAccount:group:conjur-root-admins",
  "MyAccount:group:ops-admin",
  "MyAccount:host:www-01",
  "MyAccount:layer:app-layer",
  "MyAccount:host:tests_machine",
  "MyAccount:group:tests_machine"
]

As a user can configure the same ID for different objects with two different types, we need to enable the user to filter it according to the object ID as well.
Conjur show -o group -i tests_machine
[
….]

**Comment by sigalsax** [comment]
> conjur show -i "ansible" -k layer

I think it would be a better UX if it would be something along the lines of "layer:ansible" because flags can be annoying and repetitive
